version: '3.8'

# ------------------ YAML 锚点定义 (最佳实践) ------------------
# 将可复用的模板定义在顶层，而不是 services 内部

# 为Go服务的通用构建配置创建一个锚点
x-go-build: &go-build
  context: .
  dockerfile: Dockerfile

# 为Go服务的通用属性 (如依赖) 创建一个锚_go-build
x-go-service-base: &go-service-base
  # 使用上面的 build 锚点
  build:
    <<: *go-build
  # 所有服务都依赖于基础设施
#  depends_on:
#    - jaeger
#    - kafka
#  # 将通用的环境变量放在这里
#  environment:
#    JAEGER_ENDPOINT: http://jaeger:14268/api/traces
#    KAFKA_BROKERS: kafka:29092
#    ZK_SERVERS: zookeeper:2181

# ------------------ 服务定义 ------------------
services:
  order-service:
    <<: *go-service-base
    container_name: order-service
    build:
      args:
        SERVICE_NAME: order-service
    ports:
      - "8081:8081"
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      KAFKA_BROKERS: kafka:29092
      FRAUD_DETECTION_SERVICE_URL: http://fraud-detection-service:8085/check
      INVENTORY_RESERVE_URL: http://inventory-service:8082/reserve_stock
      INVENTORY_RELEASE_URL: http://inventory-service:8082/release_stock
      PRICING_SERVICE_URL: http://pricing-service:8084/calculate_price
      PROMOTION_SERVICE_URL: http://promotion-service:8087/get_promo_price
      SHIPPING_SERVICE_URL: http://shipping-service:8086/get_quote

  inventory-service:
    <<: *go-service-base
    container_name: inventory-service
    build:
      args:
        SERVICE_NAME: inventory-service
    ports:
      - "8082:8082"

  notification-service:
    <<: *go-service-base
    container_name: notification-service
    build:
      args:
        SERVICE_NAME: notification-service

  pricing-service:
    <<: *go-service-base
    container_name: pricing-service
    build:
      args:
        SERVICE_NAME: pricing-service
    ports:
      - "8084:8084"

  fraud-detection-service:
    <<: *go-service-base
    container_name: fraud-detection-service
    build:
      args:
        SERVICE_NAME: fraud-detection-service
    ports:
      - "8085:8085"

  shipping-service:
    <<: *go-service-base
    container_name: shipping-service
    build:
      args:
        SERVICE_NAME: shipping-service
    ports:
      - "8086:8086"

  promotion-service:
    <<: *go-service-base
    container_name: promotion-service
    build:
      args:
        SERVICE_NAME: promotion-service
    ports:
      - "8087:8087"

# 定义网络
networks:
  default:
    driver: bridge