# k8s/03-services/fraud-detection-service.yaml

# ----------------- Fraud Detection Service Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-service
  namespace: jaeger-demo
  labels:
    app: fraud-detection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-service
  template:
    metadata:
      labels:
        app: fraud-detection-service
    spec:
      containers:
        - name: fraud-detection-service
          # 镜像地址来自 build-all.sh 脚本
          image: jaeger-demo/fraud-detection-service:latest
          imagePullPolicy: Never  # 使用本地镜像，不从远程仓库拉取
          ports:
            - containerPort: 8085
          envFrom: # 从 ConfigMap 'app-config' 注入环境变量
            - configMapRef:
                name: app-config
---

# ----------------- Fraud Detection Service Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: jaeger-demo
spec:
  selector:
    app: fraud-detection-service
  ports:
    - port: 8085
      targetPort: 8085
  # ClusterIP 类型的服务，仅在集群内部可见
  type: ClusterIP 