# k8s/03-services/inventory-service.yaml

# ----------------- Inventory Service Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: jaeger-demo
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          # 镜像地址来自 build-all.sh 脚本
          image: crpi-4dj6hqy7jwojfw8v.cn-shanghai.personal.cr.aliyuncs.com/yingjiewang/inventory-service:latest
          ports:
            - containerPort: 8082
          envFrom: # 从 ConfigMap 'app-config' 注入环境变量
            - configMapRef:
                name: app-config
---

# ----------------- Inventory Service Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: jaeger-demo
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8082
      targetPort: 8082
  # ClusterIP 类型的服务，仅在集群内部可见
  type: ClusterIP 