# k8s/03-services/inventory-service.yaml

# ----------------- Inventory Service Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: nexus
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          # 镜像地址来自 build-all.sh 脚本
          image: yingjiewang/nexus-inventory:latest
          imagePullPolicy: Never  # 使用本地镜像，不从远程仓库拉取
          ports:
            - containerPort: 8082
          envFrom: # 从 ConfigMap 'app-config' 注入环境变量
            - configMapRef:
                name: app-config
---

# ----------------- Inventory Service Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: nexus
spec:
  selector:
    app: inventory-service
  ports:
    - name: http-web
      port: 8082
      targetPort: 8082
  # ClusterIP 类型的服务，仅在集群内部可见
  type: ClusterIP 