# k8s/03-services/order-service.yaml

# ----------------- Order Service Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: jaeger-demo
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          # 镜像地址来自 build-all.sh 脚本
          image: jaeger-demo/order-service:latest
          imagePullPolicy: Never  # 使用本地镜像，不从远程仓库拉取
          ports:
            - containerPort: 8081
          envFrom: # 从 ConfigMap 'app-config' 注入环境变量
            - configMapRef:
                name: app-config
---

# ----------------- Order Service Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: jaeger-demo
spec:
  selector:
    app: order-service
  ports:
    - port: 8081
      targetPort: 8081
  # ClusterIP 类型的服务，仅在集群内部可见
  type: ClusterIP