# ----------------- Order Service v2 Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-v2 # 名称改为 v2
  namespace: jaeger-demo
  labels:
    app: order-service-v2 # 标签改为 v2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-v2
      version: v2
  template:
    metadata:
      labels:
        app: order-service-v2
        version: v2
    spec:
      containers:
        - name: order-service
          # 假设这是你的新版本镜像
          image: jaeger-demo/order-service-v2:latest
          imagePullPolicy: IfNotPresent # 使用本地镜像
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config