# k8s/03-services/promotion-service.yaml

# ----------------- Promotion Service Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: nexus
  labels:
    app: promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      containers:
        - name: promotion-service
          # 镜像地址来自 build-all.sh 脚本
          image: yingjiewang/nexus-order:latest
          imagePullPolicy: Never  # 使用本地镜像，不从远程仓库拉取
          ports:
            - containerPort: 8087
          envFrom: # 从 ConfigMap 'app-config' 注入环境变量
            - configMapRef:
                name: app-config
---

# ----------------- Promotion Service Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: nexus
spec:
  selector:
    app: promotion-service
  ports:
    - name: http-web
      port: 8087
      targetPort: 8087
  # ClusterIP 类型的服务，仅在集群内部可见
  type: ClusterIP 