# k8s/01-infra/redis.yaml
# 定义一个 PersistentVolumeClaim (PVC) 用于 Redis 数据持久化
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# 定义 Redis 的 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pvc

---
# 定义 Redis 的 Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: database
spec:
  ports:
  - port: 6379
  selector:
    app: redis
  type: ClusterIP
