# k8s/05-ingress/order-service-route.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: order-service-route
  namespace: jaeger-demo
spec:
  ingressClassName: apisix
  http:
    - name: order-rule-passthrough
      match:
        hosts:
          - jaeger-demo.local
        paths:
          - /*
      # 【核心修改】
      # 移除 backends 数组和 weight，改为单一的 backend。
      # APISIX 的任务只是把流量转发给 order-service 这个 K8s Service。
      # 它不再关心 order-service 背后有几个版本，这些由 Istio 处理。
      backend:
        serviceName: order-service
        servicePort: 8081