# k8s/05-ingress/order-service-route.yaml (兼容旧版本的写法)
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: order-service-route
  namespace: jaeger-demo
spec:
  ingressClassName: apisix
  http:
    - name: order-rule-grayscale_v3
      match:
        hosts:
          - jaeger-demo.local
        paths:
          - /*
      # 【核心修改】
      # 不使用 trafficSplit 插件，而是直接在 backends 数组中定义多个服务
      # 并为每个服务指定 weight (权重)
      backends:
        - serviceName: order-service      # 指向 v1 (稳定版) Service
          servicePort: 8081
          weight: 100                    # 分配 90% 的流量
#        - serviceName: order-service-v2   # 指向 v2 (新版) Service
#          servicePort: 8081
#          weight: 100                      # 分配 10% 的流量